# -*- coding: utf-8 -*-
"""Natural Language Processing (NLP) Application.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wALZJelyKISa0JQtDzYq7CKUOSHqJ0Cn
"""

import pandas as pd
import nltk
from nltk import word_tokenize, pos_tag, ngrams
from nltk.corpus import stopwords
from nltk import FreqDist
from collections import Counter
import io

# Download required NLTK data
nltk.download('punkt')
nltk.download('averaged_perceptron_tagger')
nltk.download('stopwords')
nltk.download('punkt_tab')
nltk.download('averaged_perceptron_tagger_eng')


# Input cleaned CSV data as a string
file_path = '/content/cleaned_worldbank_country_stats.csv'

# Make a copy of the original dataset
df_cleaned = pd.read_csv(file_path)

# Function to tokenize country names
def tokenize_name(name):
    if not isinstance(name, str):
        return []
    return word_tokenize(name.lower())

# Apply tokenization
df_cleaned['tokens'] = df_cleaned['country'].apply(tokenize_name)
df_cleaned['word_count'] = df_cleaned['tokens'].apply(len)

# Filter stopwords for n-gram analysis
stop_words = set(stopwords.words('english'))

# Store results in a dictionary
results = {}

# H1: Correlate word count with population density (countries only)
countries_df = df_cleaned[df_cleaned['is_region'] == 0]
correlation = countries_df['word_count'].corr(countries_df['density'])
results['H1'] = {
    'Analysis': 'Correlation between word count and population density',
    'Result': f"{correlation:.3f}",
    'Interpretation': "Weak positive correlation; multi-word names slightly associated with higher density." if correlation > 0 else "No strong correlation; word count does not strongly predict density."
}


# H2: Word frequency analysis with FreqDist
all_words = [word for tokens in df_cleaned['tokens'] for word in tokens if word not in stop_words]
freq_dist = FreqDist(all_words)
top_words = freq_dist.most_common(5)
results['H2'] = {
    'Analysis': 'Top 5 most common words (excluding stopwords)',
    'Result': ', '.join([f"{word}: {freq}" for word, freq in top_words]),
    'Interpretation': "Geographic/political terms like 'republic' and 'islands' are frequent, confirming hypothesis."
}

# H3: Bigram analysis
bigrams = [bigram for tokens in df_cleaned['tokens'] for bigram in ngrams(tokens, 2) if all(word not in stop_words for word in bigram)]
bigram_freq = Counter(bigrams)
top_bigrams = bigram_freq.most_common(5)
results['H3'] = {
    'Analysis': 'Top 5 most common bigrams (excluding stopwords)',
    'Result': ', '.join([f"{' '.join(bigram)}: {freq}" for bigram, freq in top_bigrams]),
    'Interpretation': "Bigrams like 'united arab' and 'south africa' indicate meaningful geographic/political phrases."
}

# H4: Parts of speech analysis
pos_tags = [pos_tag(tokens) for tokens in df_cleaned['tokens']]
pos_counts = Counter(tag for tags in pos_tags for _, tag in tags if _ not in stop_words)
top_pos = pos_counts.most_common()
results['H4'] = {
    'Analysis': 'Parts of speech distribution (excluding stopwords)',
    'Result': ', '.join([f"{tag}: {count}" for tag, count in top_pos]),
    'Interpretation': "Nouns (NN, NNP) dominate, with adjectives (JJ) less common but present in multi-word names."
}


# H5: Compare word counts between countries and regions
avg_word_count_countries = countries_df['word_count'].mean()
avg_word_count_regions = df_cleaned[df_cleaned['is_region'] == 1]['word_count'].mean()
results['H5'] = {
    'Analysis': 'Average word count - Countries vs. Regions',
    'Result': f"Countries: {avg_word_count_countries:.2f}, Regions: {avg_word_count_regions:.2f}",
    'Interpretation': "Regions have higher average word counts, confirming hypothesis of more complex names."
}

# Convert results to DataFrame
results_df = pd.DataFrame.from_dict(results, orient='index')

# Display the results table
display(results_df)

# Save results to a CSV file
results_df.to_csv('nlp_analysis_results.csv')